# Generated by Django 3.2.8 on 2021-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('poster_url', models.URLField()),
                ('synopsis', models.CharField(max_length=1000)),
                ('cast', models.CharField(max_length=500)),
            ],
        ),
    ]
