# Generated by Django 3.2.8 on 2021-10-29 14:51
import json

from django.db import migrations, models
from django.conf import settings

def populate_movies(apps, schema_editor):
    filepath = str(settings.BASE_DIR) + '\movie\data\movies-with-images.json'
    Movie = apps.get_model('movie', 'Movie')
    with open(filepath, encoding="utf8") as f:
        raw_data = f.read()
        data = json.loads(raw_data)
        for movie_item in data:
            title = movie_item.get('title')
            date = movie_item.get('release_date')
            poster = movie_item.get('poster')
            overview = movie_item.get('overview')
            movie = Movie(movie_title=title, release_date=date, poster_url=poster, synopsis=overview)
            movie.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('release_date', models.IntegerField()),
                ('poster_url', models.URLField()),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.RunPython(populate_movies),
    ]
