# Generated by Django 3.2.8 on 2021-10-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
